const { castValue } = require('./typeCaster');

/**
 * Transforms, type-casts, and validates parsed spreadsheet rows against a schema mapping.
 *
 * @param {object} params
 * @param {Array<Record<string, any>>} params.rows - Raw parsed rows from spreadsheet.
 * @param {Record<string, string>} params.mapping - Map of spreadsheet_col -> target_field.
 * @param {object} params.normalizedSchema - Schema generated by normalizeTargetSchema.
 * @returns {{ data: Array<Record<string, any>>, errors: Array<{ row: number, errors: string[], raw: Record<string, any> }>, stats: { total: number, valid: number, invalid: number } }}
 */
function transformRows(params) {
  const { rows = [], mapping = {}, normalizedSchema } = params;
  const fields = normalizedSchema.fields;

  // Invert mapping for quick lookup: targetField -> spreadsheetCol
  // Or iterate mapping entries: for (col, targetField) of mapping
  const mappingEntries = Object.entries(mapping);

  const validData = [];
  const rowErrors = [];

  for (let i = 0; i < rows.length; i++) {
    const rawRow = rows[i];
    const rowNumber = i + 1;
    const transformedRow = {};

    // Apply mapping
    for (const [colName, targetField] of mappingEntries) {
      const fieldDef = fields[targetField];
      if (!fieldDef) continue;

      const rawVal = rawRow[colName];
      const castedVal = castValue(rawVal, fieldDef.type);
      transformedRow[targetField] = castedVal;
    }

    // Also populate any unmapped target fields as null/undefined so schema validator can evaluate required constraints
    for (const targetField of Object.keys(fields)) {
      if (!(targetField in transformedRow)) {
        transformedRow[targetField] = null;
      }
    }

    // Validate transformed row
    const validationResult = normalizedSchema.validateRow(transformedRow);

    if (validationResult.success) {
      validData.push(validationResult.data || transformedRow);
    } else {
      rowErrors.push({
        row: rowNumber,
        errors: validationResult.errors || ['Validation failed'],
        raw: rawRow,
      });
    }
  }

  return {
    data: validData,
    errors: rowErrors,
    stats: {
      total: rows.length,
      valid: validData.length,
      invalid: rowErrors.length,
    },
  };
}

module.exports = {
  transformRows,
};
